<a href="https://colab.research.google.com/github/PSriChandana/Data-Imputation/blob/main/Data_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("GTPvar.csv",index_col=0)

In [ ]:
data.isnull().sum(axis=1)
#Aggregating the number of null values per row, for any column,
#because that gives us the number of missing values , so the number of
# missing variables for each row

1      0
2      0
3      0
4      0
5      3
      ..
96     0
97     5
98     0
99     0
100    0
Length: 100, dtype: int64

In [ ]:
data["NApresent"]=data.isnull().sum(axis=1)

In [ ]:
data["NApresent"].value_counts()
#this gives us the number of missing values
#with respect to how many rows

NApresent
0    58
1    18
3    11
2    10
4     2
5     1
Name: count, dtype: int64

In [ ]:
#