<a href="https://colab.research.google.com/github/PSriChandana/Data-Imputation/blob/main/Data_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("GTPvar.csv",index_col=0)

In [ ]:
data.isnull().sum(axis=1)
#Aggregating the number of null values per row, for any column,
#because that gives us the number of missing values , so the number of
# missing variables for each row

1      0
2      0
3      0
4      0
5      3
      ..
96     0
97     5
98     0
99     0
100    0
Length: 100, dtype: int64

In [ ]:
data["NApresent"]=data.isnull().sum(axis=1)

In [ ]:
data["NApresent"].value_counts()
#this gives us the number of missing values
#with respect to how many rows

NApresent
0    58
1    18
3    11
2    10
4     2
5     1
Name: count, dtype: int64

In [ ]:
#now we filter out the rows whose number of NApresent is 0
df=data[data.NApresent==0]
#because the NApresent doesnt give any further information
df=df.drop("NApresent",axis=1)

In [ ]:
#Converting the pandas DataFrame to Numpy array
df_mat=df.to_numpy()
print(df_mat)

[[0.26606623 0.55848023 0.89411896 0.64492968 2.3635951 ]
 [0.55203478 0.66692795 0.6164923  0.3362703  2.17172534]
 [0.4765388  0.63467968 0.68067411 0.41038676 2.20227935]
 [0.67096538 0.80444354 0.73377633 0.3961528  2.60533805]
 [0.49950754 0.5828923  0.50601054 0.26235925 1.85076962]
 [0.71739204 0.81488328 0.6706547  0.33144364 2.53437367]
 [0.27667065 0.55834919 0.8733656  0.62502493 2.33341036]
 [0.4908676  0.73582834 0.90782267 0.58989551 2.72441411]
 [0.75115896 0.81122971 0.59642052 0.26146984 2.42027903]
 [0.79622514 0.85386914 0.61701459 0.26487205 2.53198091]
 [0.89260969 0.92074126 0.59980377 0.22260314 2.63575786]
 [0.24330746 0.48205242 0.74546579 0.53138926 2.00221492]
 [0.21571797 0.50867703 0.86565569 0.63671623 2.22676692]
 [0.55578904 0.66876453 0.61388733 0.33305915 2.17150005]
 [0.20429597 0.47131224 0.79354969 0.58175461 2.05091251]
 [0.19630342 0.50051666 0.88249463 0.65604612 2.23536082]
 [0.1277004  0.45174688 0.89179139 0.68374292 2.15498159]
 [0.32205849 0.53059897 0.71606253 0.48444514 2.05316512]
 [0.48538679 0.62992594 0.65166114 0.38431804 2.15129192]
 [0.73186213 0.81657749 0.64705329 0.30809835 2.50359127]
 [0.78528214 0.86160492 0.6575727  0.30089494 2.60535469]
 [0.55332057 0.63980677 0.54571077 0.27864237 2.01748047]
 [0.54337717 0.62592201 0.52989201 0.26877231 1.9679635 ]
 [0.85234938 0.87225717 0.55523407 0.19839538 2.478236  ]
 [0.74462213 0.76586539 0.4947591  0.18116629 2.1864129 ]
 [0.63461921 0.73348858 0.625075   0.31892266 2.31210545]
 [0.5511297  0.75653096 0.84390226 0.52047104 2.67203396]
 [0.09473537 0.39694056 0.81724885 0.63314676 1.94207154]
 [0.75246766 0.81163808 0.59492857 0.25987821 2.41891252]
 [0.445797   0.5987687  0.64943807 0.39416403 2.08816779]
 [0.36915726 0.57921912 0.74780454 0.49626624 2.19244717]
 [0.4622438  0.58157059 0.57444897 0.32867378 1.94693715]
 [0.64784226 0.80104023 0.76973845 0.43204073 2.65066166]
 [0.22005408 0.45927064 0.73287374 0.52804373 1.94024219]
 [0.39945687 0.62567861 0.80645883 0.53479557 2.36638988]
 [0.44161529 0.63687038 0.75345151 0.47952246 2.31145966]
 [0.16215013 0.47489053 0.88373146 0.66709158 2.1878637 ]
 [0.5816018  0.61018341 0.41663623 0.16592583 1.77434727]
 [0.37643886 0.65548219 0.92585068 0.6381325  2.59590423]
 [0.77676644 0.79796839 0.51370354 0.18703479 2.27547315]
 [0.74100094 0.82429937 0.64890031 0.30690438 2.521105  ]
 [0.48412596 0.64246164 0.68566079 0.41218859 2.22443698]
 [0.46533076 0.66405092 0.77623197 0.49097269 2.39658635]
 [0.61579518 0.66920883 0.49943893 0.22284173 2.00728468]
 [0.28333291 0.56079898 0.86670444 0.61767774 2.32851406]
 [0.428907   0.55164044 0.56327356 0.32943979 1.87326079]
 [0.29244309 0.61593752 0.98802631 0.71312626 2.60953317]
 [0.29538909 0.551533   0.82014858 0.57647632 2.24354699]
 [0.31013475 0.62002583 0.96425    0.68869199 2.58310257]
 [0.09654903 0.38948359 0.79497534 0.61459798 1.89560594]
 [0.62990077 0.72642252 0.61636635 0.31326667 2.28595631]
 [0.26043749 0.53994738 0.85828416 0.61760116 2.27627019]
 [0.60592518 0.66358275 0.50427844 0.22965898 2.00344534]
 [0.55077111 0.71765267 0.74667718 0.44193857 2.45703954]
 [0.7062568  0.82277135 0.71196659 0.36813274 2.60912748]
 [0.75216236 0.82268828 0.62334668 0.28295324 2.48115056]
 [0.53468164 0.70935065 0.75675551 0.45482236 2.45561016]
 [0.68292238 0.726436   0.5142846  0.21510596 2.13874893]]

In [ ]:
#RANK OF MATRIX
np.linalg.matrix_rank(df_mat)
#Rank=5,rank is full, so no null space
#this shows that there is no relationship between the variables
#matrix_rank uses SVD function,

np.int64(5)

In [ ]:
#to use SVD decomposition-input is a matrix
#returns -1. Unitary array, 2. vector of all singular values
#3. another unitary matrix
v,s,u=np.linalg.svd(df_mat)
#v is dimension of 5,5 u is dimention of 58,58
#singular values are square roots of eigen values

Q. How and Why do you recompute the eigen Values?

The eigenvalues (or singular values) are very close to zero but not exactly zero, so the matrix is mathematically full rank. However, for numerical computations, a tolerance is chosen. Eigenvalues below this tolerance are treated as zero, giving an effective (numerical) rank that is smaller than the mathematical rank.


```
# This is formatted as code
```

In [ ]:
#new rank is 2
#set Tolerance
tol=1e-8
#Removing columns that are lesser than the tolerance
rank=min(df_mat.shape)-np.abs(s)[::-1].searchsorted(tol)
#Choosing the null space relation
#Whats this??
A=v[:,rank:]
A=A.T
print(A)

[[-0.15015901  0.02785362 -0.12893678 ...  0.11136363 -0.15220412
  -0.07864265]
 [ 0.1876312  -0.07642821  0.03322772 ... -0.13217527 -0.19255104
  -0.11505339]
 [-0.10124339 -0.06200441 -0.20464661 ...  0.15160642 -0.05121379
   0.25492093]
 ...
 [-0.12112925 -0.15191593  0.01599799 ...  0.90255175 -0.01495931
  -0.09584648]
 [-0.08432312  0.00354188 -0.12687008 ... -0.01233756  0.92760459
  -0.01984074]
 [-0.13197935 -0.13587143  0.15834893 ... -0.07250641 -0.03580418
   0.8865872 ]]